### ISSUE TITLE
When starting a timer with "Show record tag selection" set to true, a selection dialog is not shown when the activity only has general tags.

### ISSUE THREAD

**Issue by bahalbach** [Razeeman/Android-SimpleTimeTracker#26] opened 2021-12-24 09:58 UTC
I think that is not quite intended behavior.

**Comment by Razeeman** [comment] 2021-12-27 09:22
Thank you for highlighting this problem!

That's an intended behaviour although not really intuitive I guess. The reason is to prevent showing record tag selection on every activity after adding just one general tag which is at least for me would be an inconvenience. Current realisation provides some control on which activities show tag selection even after checking this setting (if activity has record tags assigned to it - show selection, if there is only general tags - don't show).

So to summarise the problem: this setting should show tag selection if there are record tags, but still provide some control on which activities to show it.

For now I see it this way: if there are no record tags added (general or assigned to some activity) - hide this setting, because it's no use for the user, otherwise - show it and show a button (like for manual ordering) which open a screen that allows to select activities that actually need to open tag selection. This way as a user if I want tag selection to show on activity start but not on every activity - I can still do what.

What do you think?

**Comment by bahalbach** [comment] 2021-12-27 10:00
Oh I see why you did it this way. That makes sense.

I think what you have now is actually better than that. Maybe have a setting "Show record tag selection with only general tags" that shows up when "Show record tag selection" is true (like "Close after selecting one tag")?

**Comment by Razeeman** [comment] 2021-12-27 10:14
Well in current realisation if user has a general tag and use it only on some activities and want the tag selection to show - they will need to create some dummy record tags assigned to these activities for tag selection to show, which is not intuitive.   "Show record tag selection with only general tags" would still open tag selection on every activity, so in the end I think after selecting "Show record tag selection" it's still needed some control to choose which activities actually need to show tag selection and which don't.

**Comment by bahalbach** [comment] 2021-12-27 10:16
Ah I see :)

**Comment by kmantel** [comment] 2023-01-08 12:28
Hi, I also think the current behavior is a bit unintuitive. I'm using the dummy tag workaround right now because for my use case I'd like the tag selection on every activity. Would you be amenable to including another sub-setting as mentioned [above](https://github.com/Razeeman/Android-SimpleTimeTracker/issues/26#issuecomment-1001481931)? Are you open to merging #27 if updated?

**Comment by Razeeman** [comment] 2023-01-09 10:20
@kmantel Hello! Yes, it wouldn't be ideal, but I still can't find a better solution. @bahalbach Can you implement this suggestion in your merge or should I do it?

**Comment by bahalbach** [comment] 2023-01-31 05:11
@Razeeman I haven't done anything with android in the last year so I think you would be able to do it much more quickly. If you don't have time I can try.

**Closed as completed** 2023-02-04 19:54 UTC

**Comment by Razeeman** [comment] 2023-02-04 20:06
Merged PR and added a settings to show tag selection even with only general tags. Will be in the next update. Thank you for the help!
