### ISSUE TITLE
[Feature] Automatic cloud backup

### ISSUE THREAD

**Issue by rasmussehlin** [Razeeman/Android-SimpleTimeTracker#63] opened 2022-12-12 16:07 UTC
As a user I'd like to be able to configure automatic backups to the cloud (read: Google Drive) with specified intervals. This would also be applicable to spreadsheet exports.

**Why?**
- Data is stored safely off-phone
    - The internal storage of phone shouldn't be the main backup medium 
- Data is accessible from PC

**Comment by 1over137** [comment] 2022-12-20 03:05
We can also just have the database exposed in a user accessible location, then you can use Syncthing or something similar.

**Comment by rasmussehlin** [comment] 2022-12-20 18:30
Yeah, that's also a way to solve this use case. However, I'd argue that it isn't very user friendly. I'd appreciate it if I didn't have to configure any third party app in order to get the functionality that I want.

Depends on who the owner of the app aims to have as user.

**Comment by Razeeman** [comment] 2023-01-14 09:32
#40 

Hello! Thank you for the suggestion. Automatic cloud backups indeed would be great, but it would require certain permissions added and because this app positioned as simple and safe I'm on the fence about it.

Still looking into it thought.

**Comment by rasmussehlin** [comment] 2023-01-16 06:10
I see, that's reasonable. But aren't permissions optional until you use said feature? Or do you mean it affects how the app is presented in Play store/from Google?

**Comment by Razeeman** [comment] 2023-01-16 11:31
@rasmussehlin Yes, I think it is a turnoff to see that the app requires a lot of permissions, at least for me. So I'm very hesitated to add new ones.

**Comment by rasmussehlin** [comment] 2023-01-16 11:54
I agree with you that it can be a turnoff. Is app-data synchronized with your Google account though? Perhaps that's good enough for backup purposes. I used to use an app called Timesheet. However, I hadn't setup backups (it's possible in that app) so when my phone broke I lost a lot of data.

Well, perhaps a solution is to make sure that the database is accessible. But I'm guessing that could also be a security concern? In regards to other apps getting access to the data.

**Comment by gnorman7** [comment] 2023-01-16 20:13
I just want to jump in and comment that having an automatic export feature to Google Drive would be huge. As someone who recently was looking at a few time tracking apps, having at least read access from the computer is very attractive. The Toggl time tracker (1M+ downloads on play store) allows for syncing between devices and the Boosted Time Tracker (1M+ downloads on play store) allows for backup / export to google drive. I think implementing this with the minimal amount of permissions would be a worthwhile tradeoff. You add a few permissions in the app stores, but then the user doesn't need to use the feature.

Also, if the app is clarified as being "open source", lots of people who have security concerns will feel better. In other words, the people who usually are the most worried about security understand the concept of "open source" and that will make them less hesitant to trust the app.

**Comment by Razeeman** [comment] 2023-01-19 10:30
Spent more time on this and it seems there is a way to do it without adding more permissions. Still testing it, but looks promising. If everything would work ok, it will probably be in the next update. Auto csv export should also works this way.

**Comment by rasmussehlin** [comment] 2023-01-20 05:56
Awesome! Great job @Razeeman! 🙌

**Comment by gnorman7** [comment] 2023-02-01 19:36
Thank you for adding this in! Related to this issue, I'm experiencing a bug where the app hangs after the automatic export. I.e., there's just the loading icon (for hours). Closing and restarting the app fixes this. The file that was automatically exported appears to be fine! I'm not sure if this warrants its own issue, as it's a very small problem.

Let me know if there is anything I can do to help you reproduce the problem in an emulator or likewise.

**Comment by Razeeman** [comment] 2023-02-04 09:42
@gnorman7 That's weird, thank you for the feedback. This loader works the same way as for the manual backup. Does manual backup works correctly without this issue for you?

**Comment by gnorman7** [comment] 2023-02-05 22:34
Yes, the manual backup has never caused any issues

**Comment by Razeeman** [comment] 2023-02-07 15:42
@gnorman7 can you tell a model of your phone and android os version please?

**Comment by 1over137** [comment] 2023-02-08 02:32
I am experiencing the same issue. I didn't personally connect it to the auto-back up though. The app would appear loading every time I wake up in the morning and the only way to do anything is to force close it. 
I have a Mi Max 3 running Android 12 (LineageOS)

**Comment by Razeeman** [comment] 2024-01-17 09:14
This bug is probably fixed, have not encountered it for awhile.

**Closed as completed by Razeeman** 2024-01-17 09:14 UTC
