### ISSUE TITLE
[Bug] Changing tag selection of running activity impossible (ver 1.34)

### ISSUE THREAD

**Issue by Zocker1999NET** [Razeeman/Android-SimpleTimeTracker#149] opened 2024-01-16 23:01 UTC
This bug became instantly visible after F-Droid upgraded the app from 1.33 to 1.34.

Running activities cannot have any (record) tags applied to them. This happens in all of the following circumstances:
- with “show record tag selection“ enabled, a selected tag is not saved
- changing tags on *running* activities is not saved
	- (changing tags on stopped entries does still work)
- when a *running* activity has a tag applied, all get cleared when trying to change the tag selection. To reproduce:
	1. add a tag to a saved, *stopped* entry (or select one with some tags)
	2. “continue” this stopped entry using the edit screen, continuing the timer
	3. now the tags are still saved
	4. edit the now *running* activity, changing the tag selection (tested adding & removing one tag)
	5. see how the running activity looses all tags saved
- “repeating” a former activity with tags does not work either
	- the then running activity has no tags applied
	- (the saved entry is unchanged / keeps its tags)

It is not just a rendering issue as the edit screen for that entry does also display no tags as applied and selecting a tag once in that edit screen works as before.

OS: Android 13 (Lineage OS with microG)
Phone: Fairphone 4
App Version: 1.34
Source: F-Droid

**Comment by Zocker1999NET** [comment] 2024-01-17 00:49
okay, closing this now, seems to be a one off error:
- couldn’t reproduce in an emulator testing following scenarios:
	- ver 1.34, clean start
	- ver 1.34, with my data imported
	- ver 1.33, clean start, then upgrade to ver 1.34
	- everything also tested with the same settings in the app
- couldn’t reproduce on my phone in work mode with a clear start either

after that, I exported my current data & reimported it again. Everything works now, could not find out why.

**Comment by Zocker1999NET** [comment] 2024-01-17 00:59
written too early (sorry for the notifies), the bug reappeared after doing a little bit more stuff. I cannot pin it down exactly, it started again after I changed the time on the current running entry & pressed “change (time of adjacent recordings)”.

Further, I found out:
- If an activity was started with a tag, but it is bugged, and then I force close app & re-open it, the tag is there on the running activity.
- However, if an activity was started with a tag which is bugged, then another activity is started stopping the first one (multi-tasking disabled), then force closing, the saved record still has no tag.

If I find more time this week, I will record a video showing the bug.

**Comment by Razeeman** [comment] 2024-01-17 15:39
Hello! Thank you very much for the feedback. Was able to reproduce this bug. Seems like it is caused by the data cache not updating properly. Will try to fix this in the next update.

**Comment by Razeeman** [comment] 2024-01-23 06:09
It should be fixed in the latest release 1.35. Please reopen if it isn't. Thanks again for pointing this out!

**Closed as completed by Razeeman** 2024-01-23 06:09 UTC

**Comment by Zocker1999NET** [comment] 2024-02-03 14:52
Thanks for fixing this bug that fast  :heart:. This issue was not appearing since I updated 1 week ago.
