### ISSUE TITLE
[Bug] Aggregated Time for the Current Month Wrong

### ISSUE THREAD

**Issue by th0b3n** [Razeeman/Android-SimpleTimeTracker#187] opened 2024-06-02 04:48 UTC
When I select This Month it displays 10 hours for an activity, even though I only started tracking this activity only an hour an 30 minutes ago.

**Comment by Razeeman** [comment] 2024-06-03 07:08
Hello! Thank you for the feedback. Can you please share some screenshots of the statistics for the current month (third tab) and records list for this month days (second tab)? Also can you check if the setting "shift start of day" is set to some value? Maybe it will help to identify the problem.

**Comment by Razeeman** [comment] 2024-07-19 09:18
Couldn't reproduce. Closing issue for now, please reopen if it happen again.

**Closed as completed by Razeeman** 2024-07-19 09:18 UTC
