### ISSUE TITLE
Unable to install or update app in fdroid 

### ISSUE THREAD

**Issue by IAAJL** [Razeeman/Android-SimpleTimeTracker#144] opened 2023-12-30 17:03 UTC
I tried to update app to latest version from fdroid but it is showing some error. So i tried uninstalling. 

After uninstall, i can't install the current version directly as well. The update is getting downloaded but some error occurs while installing

**Comment by Razeeman** [comment] 2024-01-16 16:15
Hello! Could this be a problem with fdroid client? Do any other apps install correctly? Maybe there is not enough space on the phone? Also installation files are available on the github https://github.com/Razeeman/Android-SimpleTimeTracker/releases

**Comment by IAAJL** [comment] 2024-01-17 09:36
No other apps seem to have this issue. I have like 50 gb internal space left.

**Comment by Razeeman** [comment] 2024-01-17 10:51
Can you please try to install from the github releases page?

**Comment by IAAJL** [comment] 2024-01-20 17:11
Nope. Not working. Package installer is crashing when i try to install the app.

**Comment by Razeeman** [comment] 2024-01-20 17:26
Do any previous versions of the app install correctly or this error appears only when installing latest version 1.34? Also can you please specify what is the error showing?

**Comment by IAAJL** [comment] 2024-01-20 17:32
1.31 and previous builds are installing fine. But 1.32 and later builds are having this issue.

**Comment by Razeeman** [comment] 2024-01-20 17:37
Can you also specify your phone model and android os version? Maybe it will help to identify the problem.

**Comment by IAAJL** [comment] 2024-01-21 19:09
Phone - pixel 5a
Version - android 14

**Comment by DuckDuckWhale** [comment] 2024-01-30 04:00
I'm also affected by this. App Installer crashes instantly and silently. After failing for a second time it prompts that App Installer keeps stopping. I'm using a Pixel 7 on Android 14. I wonder if this is an Android problem or app problem. My current installed version is 1.31 and I was unable to install the subsequent versions too.

**Comment by Razeeman** [comment] 2024-01-30 11:11
Found related issue https://github.com/uazo/cromite/issues/595

Seems like a bug introduced in the Android 14 Q1 version related to the monochrome themed app icons. Probably will be fixed in the next system update Android 14 Q2:
<img width="911" alt="image" src="https://github.com/Razeeman/Android-SimpleTimeTracker/assets/5223302/ac51491d-5a1c-419a-8cf0-1eb502096521">

There is also a code fix mentioned in the issue that could help. Unfortunately I couldn't reproduce this bug without a real device. Can you please try this version to see if the bug will be fixed?

https://drive.google.com/file/d/17msYo-6ablswvCPVuWov_Zdw8PrZCw4T/view?usp=sharing

**Comment by IAAJL** [comment] 2024-01-30 14:11
Yeah this apk works 👍

**Comment by Razeeman** [comment] 2024-01-30 14:32
Great! I'll try to release new version of the app with this fix on this weekend. Debug version, that was shared in the previous comment, installs separately from the release but data from it can be transferred to release version through a backup file.

**Comment by IAAJL** [comment] 2024-01-30 20:35
K cool

**Comment by Razeeman** [comment] 2024-03-09 15:17
The issue is probably resolved. If it is not, please reopen.

**Closed as completed by Razeeman** 2024-03-09 15:17 UTC

**Comment by Razeeman** [comment] 2024-08-26 08:56
For history, was fixed in f8be367
